### ISSUE TITLE
Intialize libdragon before main is called

### ISSUE THREAD

**Issue by giulianobelinassi** [DragonMinded/libdragon#142]
Libdragon requires the user to manually initialize its components (e,g, call `dfs_init()`). This can lead to bizarre side effects with C++ global objects, for instance, the following stacktrace:
```
#0  dma_busy () at /home/giulianob/bagunca/libdragon/src/dma.c:52                              
#1  0x801855cc in dma_read (ram_address=0x7ff758, pi_address=2907242500, len=256)              
    at /home/giulianob/bagunca/libdragon/src/dma.c:81                                          
#2  0x8017d434 in grab_sector (cart_loc=0xad490004, ram_loc=0x807ff758)
    at /home/giulianob/bagunca/libdragon/src/dragonfs.c:97             
#3  0x8017da60 in find_dirent (name=0x807ff8a8 "record.bin", cur_node=0xad490004)
    at /home/giulianob/bagunca/libdragon/src/dragonfs.c:442                    
#4  0x8017dc48 in recurse_path (path=0x802c6e78 "/record.bin", mode=1, dirent=0x807ffc68,      
    type=1) at /home/giulianob/bagunca/libdragon/src/dragonfs.c:539             
#5  0x8017e0e0 in dfs_open (path=0x802c6e78 "/record.bin")                                     
    at /home/giulianob/bagunca/libdragon/src/dragonfs.c:773                                    
#6  0x801c58fc in Find_File_Data_Libdragon::FindFirst (this=0x802c6e70,                                                                                                                        
    fname=0x802c6e60 "record.bin")                                                                                                                                                             
--Type <RET> for more, q to quit, c to continue without paging--                                                                                                                               
   pp:68                                                                                                                                                                                       
#7  0x801a2960 in Resolve_File_Single (fname=0x802c6e60 "record.bin") at /home/giulianob/bagunca/Vanilla-Conquer/common/file.cpp:15
#8  0x801a2ad0 in Resolve_File (fname=0x802c6e60 "record.bin") at /home/giulianob/bagunca/Vanilla-Conquer/common/file.cpp:34
#9  0x801ba848 in RawFileClass::Set_Name (this=0x802a0d88 <RecordFile>, filename=0x80207260 "RECORD.BIN") at /home/giulianob/bagunca/Vanilla-Conquer/common/rawfile.cpp:176
#10 0x8019a238 in BufferIOFileClass::Set_Name (this=0x802a0d88 <RecordFile>, filename=0x80207260 "RECORD.BIN") at /home/giulianob/bagunca/Vanilla-Conquer/common/bfiofile.cpp:409
#11 0x8019dfb0 in CDFileClass::Set_Name (this=0x802a0d88 <RecordFile>, filename=0x80207260 "RECORD.BIN") at /home/giulianob/bagunca/Vanilla-Conquer/common/cdfile.cpp:379
#12 0x8019bf7c in CCFileClass::CCFileClass (this=0x802a0d88 <RecordFile>, filename=0x80207260 "RECORD.BIN") at /home/giulianob/bagunca/Vanilla-Conquer/common/ccfile.cpp:67
#13 0x800a9820 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/globals.cpp:424
#14 0x800b32dc in _GLOBAL__sub_I_Debug_Quiet () at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/globals.cpp:954
#15 0x801862c4 in __do_global_ctors () at /home/giulianob/bagunca/libdragon/src/do_ctors.c:31
#16 0x8000053c in loadintvectorloop ()
```
In here, the application hangs because `dfs_init` was never called, even if the programmer wrote main to call `dfs_init` on the first line.

The only workaround to this is to initialize libdragon in the constructor of some global object D:

**Comment by meeq** [comment]
My suggestion is not to rely on global constructors for non-trivial work.

Global variables are initialized in the order in which they're declared. So their constructor will be called in the same order in which they're initialized. This is true within one translation unit. However, the initialization order across multiple translation-units is not defined by the language specification.

**Comment by rasky** [comment]
I don't think we are going to do this. There are no trivial issue with respect to order of initialization of different modules, so we still want to keep that freedom to the end user. We do rely on constructors for behind the scenes configurations (basically, as a way to extend whatever we do in entrypoint.S) but for public APIs we will keep explicit initializations.
